name: zone_js
description: A package:js facade for zone.js
version: 0.0.1
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/zone-js-dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'
  func: '>=0.1.0 <1.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
